# docker-compose.yml (in root directory)
version: '3.8'

services:
  postgres:
    container_name: ${PROJECT_NAME:-myapp}_postgres
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  www:
    container_name: ${PROJECT_NAME:-myapp}_www
    build:
      context: .
      dockerfile: apps/www/Dockerfile
      target: development
    ports:
      - "${WWW_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-myapp}
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: